version: '3'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5436:5436
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: notes
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db:
