# Generated by Django 4.1.1 on 2022-11-07 14:19

from django.db import migrations, models
from django.utils.datetime_safe import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_note_options_alter_notecomment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('created_at',), 'verbose_name': 'заметка', 'verbose_name_plural': 'заметки'},
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('alert_send_at__gte', datetime(2022, 1, 1, 0, 0)), ('alert_send_at__isnull', False)), ('alert_send_at__isnull', True), _connector='OR'), name='alert_send_at_after'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('title', 'text'), name='unique_content'),
        ),
    ]
