version: '3'

services:
  nginx:
    image: django2k-nginx:latest
    build:
      context: ..
      dockerfile: deploy/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - media:/app/src/media

  app:
    image: django2k:latest
    build:
      dockerfile: deploy/app/Dockerfile
      context: ..
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DEBUG: false
    restart: always
    volumes:
      - media:/app/src/media/

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: notes
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db:
  media:
