# Generated by Django 4.1.1 on 2022-11-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_note_options_note_alert_send_at_after_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='note',
            name='unique_content',
        ),
    ]
